bracketSpacing: true
semi: true
trailingComma: all
useTabs: false
arrowParens: always
jsxSingleQuote: false
quoteProps: as-needed
singleQuote: false
printWidth: 120
bracketSameLine: true
endOfLine: lf
overrides:
  - files: "*.ts"
    options:
      tabWidth: 4
  - files: "*.mts"
    options:
      tabWidth: 4
  - files: "*.json"
    options:
      tabWidth: 4
  - files: "*.yaml,*.yml"
    options:
      tabWidth: 2
